import type { Metadata } from "next";
import { Noto_Sans_Bengali, Roboto } from "next/font/google";
import "./globals.css";

const notoSansBengali = Noto_Sans_Bengali({
  weight: ["400", "700"],
  subsets: ["bengali"],
});

const roboto = Roboto({
  weight: ["400"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Complete IELTS Course in Bangladesh - Munzereen Shahid [2025]",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` ${notoSansBengali.className} ${roboto.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
